---
title: "Bog_Data"
author: "Andrea Phillips and Emmi Mueller; Z620: Quantitative Biodiversity, Indiana University"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
geometry: margin=2.54cm
---
```{r}
#Clear workspace, set working directory and load packages
rm(list=ls())
getwd()
#setwd("~/GitHub/QB_Project/")

require("tidyverse")
require("vegan")
require("ggplot2")
require("OTUtable")
```

```{r}
#Load bog otu data and print structure
data(otu_table)
otu_table <- as.data.frame(t(otu_table))
```

```{r}
#Print rarefaction curve and rarefy otu_table to otu.rarefy
rarecurve(x = otu_table, step = 10, col = "blue", cex = 0.6, las = 1, main = "Bog rarefaction curve")
abline(0,1, col = 'red')
#abline(v = min.N, col = 'green')
```

```{r}
#create otu_JUL07 of all bogs in first few days in JUL07
JUL07 <- c("CBE02JUL07.R1", "FBE02JUL07.R1", "HKE04JUL07.R1", "MAE04JUL07.R1", "NSE03JUL07.R1", "SSE03JUL07.R1", "TBE02JUL07.R1", "WSE03JUL07")
otu_JUL07 <- otu_table[grep(paste(JUL07, collapse = "|"), row.names(otu_table)),]
row.names(otu_JUL07) <- c("Crystal Bog", "Forestry Bog", "Hell's Kitchen", "Mary Lake", "North Sparkling Bog", "South Sparkling Bog", "Trout Bog", "West Sparkling Bog")

```

```{r}
#looking at correlations between Crystal Bog and Mary Lake on the same date 

#CBE01OCT07 and CBE27JUN07
(cor(otu_table[[24]], otu_table[[80]]))^2

#CBE27JUN07 and MAE27JUN07
(cor(otu_table[[80]], otu_table[[444]]))^2

#CBE01OCT07 and MAE01OCT07
(cor(otu_table[[24]], otu_table[[372]]))^2
```

```{r}
#spatial diversity
require("vegan")
#install.packages("sp")
require("sp")
#install.packages("gstat")
require("gstat")
#install.packages("raster")
require("raster")
#install.packages("RgoogleMaps")
require("RgoogleMaps")
#install.packages("maptools")
require("maptools")
#install.packages("rgdal")
require("rgdal")
#install.packages("simba")
require("simba")
#install.packages("gplots")
require("gplots")
#install.packages("rgeos")
require(rgeos)
require(viridis)
require(gplots)

boglocate <- read.table("NTL_MO_bogs_location.txt", header = TRUE, sep = "\t")
boglocate <- boglocate[1:8, 1:4]
otu.names <- names(otu_table)

#removed bogsbys because it just removed the first OTU from out sbys matrix

sites <- boglocate[,2]
lats <-as.numeric(boglocate[,3])
lons <-as.numeric(boglocate[,4])
bogDataPoints <- data.frame(sites, lats, lons)

palette <- brewer.pal(8, "Spectral")
bogDataPoints$colors <- palette


#Add API key
newmap <- GetMap(center = c(lat = 46.12,lon = -89.75), zoom = 11, destfile = "BogMap.png", maptype = "terrain", API_console_key = )


PlotOnStaticMap(newmap, zoom = 11, cex = 2, col = 'blue')
PlotOnStaticMap(newmap, lats, lons, cex = 3, pch = 20, col = bogDataPoints$colors, add = TRUE)

tblleg <- unique(bogDataPoints[,c("sites","colors")])
row.names(tblleg) <- NULL

legend("topright", legend = tblleg$sites, fill = tblleg$colors,bg = "white")
```

```{r}
ssad <-function(otu_table, otu){
  ad <-c(2,2)
  ad <-otu_table[, otu]
  ad = as.vector(t(x = ad))
  ad = ad[ad >0]
}

par(mfrow = c(2,2))
ct <- 0
while (ct < 4){
  otu <- sample(1:length(otu_table), 1)
  ad <- ssad(otu_table, otu)
  if (length(ad) > 10 & sum(ad >100)){
    ct <- ct + 1
    plot(density(ad), col = "red", xlab = "Site abundance", ylab = "Probability Density", main = otu.names[otu])
  }
}
```
```{r}
otu_JUL07.db <- vegdist(otu_JUL07, method = "bray", upper = TRUE, diag = TRUE)
order <- rev(attr(otu_JUL07.db, "Labels"))
levelplot(as.matrix(otu_JUL07.db)[, order], aspect = "iso", col.regions = inferno, xlab = "Bog site", ylab = "Bog site", scales = list(cex = 0.5), main = "Bray-Curtis Distance")

JUL07.ward <- hclust(otu_JUL07.db, method = "ward.D2")

par(mar = c(1,5,2,2) + 0.1)
plot(JUL07.ward, main = "Bog Sites: Ward's Clustering", ylab = "Squared Bray-Curtis Distance")


bog.pcoa <- cmdscale(otu_JUL07.db, eig = TRUE, k= 3)
explainvar1 <- round(bog.pcoa$eig[1] / sum(bog.pcoa$eig), 3) * 100
explainvar2 <- round(bog.pcoa$eig[2] / sum(bog.pcoa$eig), 3) * 100
explainvar3 <- round(bog.pcoa$eig[3] / sum(bog.pcoa$eig), 3) * 100

par(mar = c(5,5,1,2) + 0.1)

plot(bog.pcoa$points[,1], bog.pcoa$points[,2],
     xlab = paste("PCoA 1 (", explainvar1, "%)", sep = ""),
     ylab = paste("PCoA 2 (", explainvar2, "%)", sep = ""),
     pch = 16, cex = 3.0, type = "n", cex.lab = 1.2, cex.axis = 1.2, axes = FALSE)

axis(side = 1, labels = T, lwd.ticks = 2, cex.axis = 1.2, las = 1)
axis(side = 2, labels = T, lwd.ticks = 2, cex.axis = 1.2, las = 1)
abline(h = 0, v = 0, lty = 3)
box(lwd = 2)

points(bog.pcoa$points[,1], bog.pcoa$points[,2], pch = 19, cex = 3, bg = "gray", col = "gray")

text(bog.pcoa$points[,1], bog.pcoa$points[,2], labels = row.names(bog.pcoa$points))

```


```{r}
#install temporal diversity packages
#We're not sure if we're going to use this yet
package.list <- c('vegan', 'tidyr', 'dplyr', 'codyn', 'ggplot2', 'cowplot', 'MullerPlot', 'RColorBrewer', 'reshape2', 'lubridate', 'TTR', 'xtable', 'multcomp', 'pander', 'png', 'grid', 'tseries', 'nlme', 'forecast', 'emmeans')
for (package in package.list) {
  if (!require(package, character.only = TRUE, quietly = TRUE)) {
    install.packages(package, repos='http://cran.us.r-project.org')
library(package, character.only = TRUE)
  }
}

bog_loc <- read.table("~/Github/QB_Project/NTL_MO_bogs_location.txt", sep = ",", header = TRUE)
bog_loc <- unite(bog_loc, col = date, c(year, month, day), sep = "-", remove = FALSE)
bog_loc <- unite(portal, col = taxon, c(genus, species), sep = "-", remove = FALSE)

time.by.species <- group_by(bog_loc, year, plot_id) %>%
count(taxon) %>% spread(key = taxon, value = n, fill = 0)

time.by.species <- as.data.frame(time.by.species)
```

```{r}
#Set up metadata for JUL07 sites
data(metadata)
rows <- c(4971,4977,5004,5025,4982,4988,4962,4998)
metadata_JUL07 <- metadata[rows, -1]
row.names(metadata_JUL07) <- c("Crystal Bog", "Forestry Bog","Hell's Kitchen","Mary Lake","North Sparkling Bog", "Sourth Sparkling Bog", "Trout Bog", "West Sparkling Bog")
num = 1
rows <- c(4976,4981,5024,5048,4987,4997,4970,5003)
while(num < nrow(metadata_JUL07)){
  depth_current <- metadata$Depth[rows[num]]
  metadata_JUL07$Depth[num] <- depth_current
  num <- num + 1
}
metadata_JUL07 <- metadata_JUL07[,c("Depth", "DO", "Temperature")]
metadata_JUL07 <- cbind(metadata_JUL07, lats)
metadata_JUL07 <- cbind(metadata_JUL07, lons)
bogcca <- cca(otu_JUL07, metadata_JUL07)

#Mantel Test
jul07.dist <- vegdist(otu_JUL07, method = "bray", upper = TRUE, diag = TRUE)
jul07.env.dist <- vegdist(scale(metadata_JUL07), method = "euclid")

mantel(jul07.dist, jul07.env.dist)

print(jul07.dist)
#dbRDA from metadata
metadata_JUL07 <- as.matrix(metadata_JUL07)

bog.dbrda <- dbrda(otu_JUL07~ ., as.data.frame(metadata_JUL07), dist = "bray")

require("psych")
psych::corr.test(metadata_JUL07)

bog.dbrda.modO <- dbrda(jul07.dist ~ 1, as.data.frame(metadata_JUL07))
bog.dbrda.mod1 <- dbrda(jul07.dist ~ ., as.data.frame(metadata_JUL07))
bog.dbrda <- ordiR2step(bog.dbrda.modO, bog.dbrda.mod1, perm.max = 200)

bog.dbrda$call
bog.dbrda$anova
ordiplot(bog.dbrda)

permutest(bog.dbrda, permutations = 999)
envfit(bog.dbrda, metadata_JUL07, perm = 999)

dbrda.explainvar1 <- round(bog.dbrda$CCA$eig[1]/ sum(c(bog.dbrda$CCA$eig, bog.dbrda$CA$eig)), 3) * 100
dbrda.explainvar2 <- round(bog.dbrda$CCA$eig[2]/ sum(c(bog.dbrda$CCA$eig, bog.dbrda$CA$eig)), 3) * 100

par(mar = c(5,5,4,4) + 0.1)

plot(scores(bog.dbrda, display = "wa"), xlim = c(-1.3, 1.5), ylim = c(-1.1, 2.7), xlab = paste("dbRDA 1 (", dbrda.explainvar1, "%)", sep = ""), ylab = paste("dbRDA 2 (", dbrda.explainvar2, "%)", sep = ""), pch = 16, cex = 2.0, type = "n", cex.lab = 1.5, cex.axis = 1.2, axes = FALSE)

axis(side = 1, labels = T, lwd.ticks = 2, cex.axis = 1.2, las=1)
axis(side = 2, labels = T, lwd.ticks = 2, cex.axis = 1.2, las=1)
abline(h = 0, v = 0, lty = 3)
box(lwd = 2)

points(scores(bog.dbrda, display = "wa"), pch = 19, cex = 3, bg = "gray", col = "gray")
text(scores(bog.dbrda, display = "wa"), labels = row.names(scores(bog.dbrda, display = "wa")))

vectors <- scores(bog.dbrda, display = "bp")

arrows(0, 0, vectors[,1], vectors[,2], lwd = 2, lty = 1, length = 0.2, col = "red")
text(vectors[,1], vectors[,2], pos = 3, labels = row.names(vectors))
axis(side=3, lwd.ticks = 2, cex.axis=1.2, las = 1, col = "red", lwd = 2.2, at = pretty(range(vectors[,1]))*2, labels = pretty(range(vectors[,1])))
axis(side=4, lwd.ticks = 2, cex.axis=1.2, las = 1, col = "red", lwd = 2.2, at = pretty(range(vectors[,2]))*2, labels = pretty(range(vectors[,2])))
```

```{r}
bog.pcoa <- cmdscale(jul07.dist, eig = TRUE, k= 3)
explainvar1 <- round(bog.pcoa$eig[1] / sum(bog.pcoa$eig), 3) * 100
explainvar2 <- round(bog.pcoa$eig[2] / sum(bog.pcoa$eig), 3) * 100
explainvar3 <- round(bog.pcoa$eig[3] / sum(bog.pcoa$eig), 3) * 100

par(mar = c(5,5,1,2) + 0.1)

plot(bog.pcoa$points[,1], bog.pcoa$points[,2], ylim = c(-0.2, 0.7),
     xlab = paste("PCoA 1 (", explainvar1, "%)", sep = ""),
     ylab = paste("PCoA 2 (", explainvar2, "%)", sep = ""),
     pch = 16, cex = 2.0, type = "n", cex.lab = 1.5, cex.axis = 1.2, axes = FALSE)

axis(side = 1, labels = T, lwd.ticks = 2, cex.axis = 1.2, las = 1)
axis(side = 2, labels = T, lwd.ticks = 2, cex.axis = 1.2, las = 1)
abline(h = 0, v = 0, lty = 3)
box(lwd = 2)

points(bog.pcoa$points[,1], bog.pcoa$points[,2], pch = 19, cex = 3, bg = "gray", col = "gray")

text(bog.pcoa$points[,1], bog.pcoa$points[,2], labels = row.names(bog.pcoa$points))

bogREL <- otu_JUL07
for (i in 1:nrow(otu_JUL07)){
  bogREL[i,] = otu_JUL07[i,]/sum(otu_JUL07[i,])
}

bog.pcoa <- add.spec.scores(bog.pcoa,bogREL,method = "pcoa.scores")

text(bog.pcoa$cproj[,1], bog.pcoa$cproj[,2], labels = row.names(bog.pcoa$cproj), col = "black")
```

```{r}
#install.packages("simba")
require("simba")

bog_loc <- read.table("NTL_MO_bogs_location.txt", header = TRUE, sep = "\t")
otu_JUL07.db <- vegdist(otu_JUL07, method = "bray", upper = TRUE, diag = TRUE)
#sites <- boglocate[,2]


lats <-as.numeric(boglocate[,3])
lons <-as.numeric(boglocate[,4])
#bogDataPoints <- data.frame(sites, lats, lons)
coord.dist <- dist(as.matrix(lats, lons))
x1 <- as.numeric(metadata_JUL07[,3])
env.dist <- vegdist(x1, "euclidean")
comm.dist.ls <- liste(otu_JUL07.db, entry = "comm")
env.dist.ls <- liste(env.dist, entry = "env")
coord.dist.ls <- liste(coord.dist, entry = "dist")
df <- data.frame(coord.dist.ls, env.dist.ls[,3], comm.dist.ls[,3])
names(df)[4:5] <- c("env", "struc")
attach(df)

par(mfrow=c(1, 3), pty = "s")
plot(env, struc, xlab = "Environmental Distance", ylab = "Bray-Curtis Dissimilarity",
     main = "Environmental Distance", col = 'SteelBlue')

OLS <- lm(struc ~ env)
OLS
abline(OLS, col = "red4")

plot(dist, struc, xlab = "Geographic Distance", ylab = "Bray-Curtis Dissimilarity",
     main = "Community\nComposition\n", col = 'darkorchid4')

OLS <- lm(struc ~ dist)
OLS
abline(OLS, col = "red4")

plot(dist, env, xlab = "Geographic Distance", ylab = "Environmental Distance", main = "Geographic Environmental\nCorrelation\n", col = "green")

OLS <- lm(env ~ dist)
OLS
abline(OLS, col = "red4")

diffslope(env, struc, dist, struc)

```